xcodebuild/build.go
If the disableProvisioningProfileSpecifier is true it will add an empty "PROVISIONING_PROFILE_SPECIFIER=" to the build options.
=> disableProvisioningProfileSpecifier and destination added:

xcodebuild/build.go, xcodebuild/build_test.go
using `CODE_SIGNING_ALLOWED=NO` instead of `CODE_SIGNING_REQUIRED=NO & CODE_SIGN_IDENTITY= & PROVISIONING_PROFILE_SPECIFIER= & PROVISIONING_PROFILE= & DEVELOPMENT_TEAM=` for disable code signing
=> using `CODE_SIGNING_ALLOWED=NO` for disabling code signing

profileutil/info_model.go
Reverts bitrise-io/go-xcode#80
Field is unused, removing.
=> Revert "Add a new private field to ProvisioningProfileInfoModel to store cont…"

xcarchive/macos.go
- The package searched on a wrong location for a wrong provisioning profile extension
`Contents/Resources/embedded.mobileprovision` => `Contents/embedded.provisionprofile`
=> TOOL-368 MacOS XcArchive embedded profile location fix

exportoptions/appstore_options.go, exportoptions/non_appstore_options.go, exportoptions/properties.go
This PR adds support to `distributionBundleIdentifier` export options property introduced in Xcode 12.
```
xcodebuild -h
....
distributionBundleIdentifier : String
Reformat archive to focus on eligible target bundle identifier.
....
```
=> Add distributionBundleIdentifier property to the exportOptions structs.

xcarchive/ios.go, xcarchive/ios_test.go, xcarchive/macos.go, xcarchive/macos_test.go, xcarchive/xcarchive.go, xcarchive/xcarchive_test.go
https://bitrise.atlassian.net/browse/STEP-192
`FindDSYMs` method of the archives (iOS and MacOS) returns all of the app `dSYM`s. The duplicated logic was also extracted.
It is possible to have multiple `dSYM`s for a project, due to the different targets (like one for the regular app and another for app clip). Previously only the last found `dSYM` file was returned by the `FindDSYMs` method, making it impossible to automatically export all of them for further usage. 
All of the `dSYM` files are collected and during iterating through the content of `BITRISE_DSYM_DIR_PATH`.
=> [STEP-192]: FindDSYMs returns all of the app dsyms

xcarchive/xcarchive.go, xcarchive/xcarchive_test.go
https://bitrise.atlassian.net/browse/STEP-303
Based on [this](https://developer.apple.com/documentation/xcode/building_your_app_to_include_debugging_information#3403353) document the generation of the build symbols is optional, so there is no need to return an error if there is not any dSYM found.
=> Returning error upon missing dSYM removed

xcodeproject/xcodeproj/target.go, xcodeproject/xcodeproj/target_test.go, xcodeproject/xcodeproj/xcodeproj.go, xcodeproject/xcodeproj/xcodeproj_test.go
This PR adds support for iOS Auto Provision step's UITest target signing, see: https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/pull/51
Changes:
- removed invalid `includeUITest` input from `Target.DependentExecutableProductTargets` (the executable target has no dependency on the related UITest targets, it works the other way around)
- new `DependesOn` returns if the target depends on another target
- `InformationPropertyList` renamed to `Infoplist` based on the `INFOPLIST_FILE` env
=> Step 917 xcode project update

xcodeproject/xcodeproj/recreate_schemes.go, xcodeproject/xcodeproj/recreate_schemes_test.go, xcodeproject/xcodeproj/scheme.go, xcodeproject/xcodeproj/target.go, xcodeproject/xcscheme/util.go, xcodeproject/xcscheme/xcscheme.go, xcodeproject/xcscheme/xcscheme_test.go
Add support to write Schemes and the feature to recreate Schemes from Targets.
- Add Marshal method to Scheme: This Marshals a usual XML file but modifies it to match the format used by Xcode
- Support all fields for Scheme (including LaunchAction, ProfileAction and ArchiveAction)
- Adding ReCreateSchemes function
=> Add Recreate Shared Schemes feature

xcodebuild/build.go, xcodebuild/build_test.go
- Requires **NO** [version update](https://semver.org/)
Adds `-resultBundlePath` xcodebuild param.
Resolves:https://bitrise.atlassian.net/browse/STEP-1192
=> Add resultBunldePath arg to xcodebuild command builder

simulator/simulator.go
This PR removes `BootSimulator` function's unnecessary inputs.
Related to: https://github.com/bitrise-steplib/steps-xcode-test/pull/168/files
=> Simplify BootSimulator.

go.mod, go.sum, xcpretty/xcpretty.go
Update to the latest version of `go-utils` and `go-steputils` packages.
=> Migrate to the new go-steputils package.

certificateutil/test_util.go
Fix for test code, broken in golang 1.17 due to additional checks:
`provided PrivateKey doesn't match parent's PublicKey`
=> Fix test cert generation

autocodesign/projectmanager/projectmanager.go
- Requires _PATCH_ [version update](https://semver.org/)
Apply the same changes as https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/pull/69 in the autocodesign package. As the Step did not use this package yet, the change needs to be applied here too.
Use cert hash to identify instead of common name. This prevents Umlauts in the common name to cause encoding problems.
=> Use cert hash to identify instead of common name.

xcarchive/ios.go, xcarchive/ios_test.go
We are about to introduce automatic codesigning to xcodebuild related steps.
The current autocodesign package offers functionality to read the codesigning requirements from an iOS project.
In the case of the `Export iOS and tvOS Xcode archive` an iOS project is not given, but a `.xcarchive` file.
This PR adds a new function to `xcarchive` package (IosArchive.ReadCodesignParameters) to read codesigning requirements from an archive file. The return value can be passed to the autocodesign lib.
The archive file does not have any information about the project's UITest targets, so the `UITestTargetBundleIDs` property of the `autocodesign.AppLayout` return value will be nil always. This means `Export iOS and tvOS Xcode archive` step can not automatically codesign the project's UITest targets.
- …
=> Read archive codesign parameters

codesign/codesign.go, codesign/codesign_test.go
If custom minimum profile validity is set, will use Bitrise-managed code signing assets.
Added support for setting Team ID, used for Apple ID authentication and filtering certificates used by codesigning.
Resolves: https://linear.app/bitrise/issue/MOB-230/xcode-archive-step-integrate-the-autocodesign-lib
=> Improved minimum profile validity, added Team ID for codesign package

autocodesign/devportalclient/appstoreconnect/appstoreconnect.go, autocodesign/devportalclient/appstoreconnect/jwt.go, go.mod, go.sum
`github.com/dgrijalva/jwt-go` is no longer maintained (https://github.com/dgrijalva/jwt-go/issues/462), it's forked as https://github.com/golang-jwt/jwt
According to [the migration guide](https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md), it's backwards compatible with the original library's 3.x version
=> Upgrade JWT library

xcarchive/ios.go, xcarchive/ios_test.go
`IosArchive.ReadCodesignParameters` used to read the code signing requirements of the given project, by analyzing the built XCArchive file.
This PR makes `IosArchive.ReadCodesignParameters` using the archive's entitlements, rather than the embedded Profiles' entitlements.
Given Profile is valid for a target, if the Profile has more capabilities enabled than what is required by the target (for example more icloud containers or additional capabilities).
- use the archive entitlements in `IosArchive.ReadCodesignParameters`
=> ReadCodesignParameters uses the archive entitlements

autocodesign/localcodesignasset/localcodesignasset.go, autocodesign/localcodesignasset/localcodesignasset_test.go, autocodesign/localcodesignasset/utils.go
This PR fixes a slice indexing issue around uitest target profile search:
```
panic: runtime error: slice bounds out of range [2:1]
goroutine 1 [running]:
github.com/bitrise-io/go-xcode/autocodesign/localcodesignasset.remove(...)
/var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/bitrise939296912/step_src/vendor/github.com/bitrise-io/go-xcode/autocodesign/localcodesignasset/utils.go:21
github.com/bitrise-io/go-xcode/autocodesign/localcodesignasset.Manager.FindCodesignAssets(0x15ad340, 0x185df48, 0x15ad320, 0x185df48, 0xc000488947, 0xa, 0xc00012529c, 0x3, 0xc00033e2a0, 0xc00013c7e0, ...)
/var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/bitrise939296912/step_src/vendor/github.com/bitrise-io/go-xcode/autocodesign/localcodesignasset/localcodesignasset.go:101 +0xecd …
```
=> Local codesign assets issue

autocodesign/autocodesign.go, autocodesign/autocodesign_test.go, autocodesign/localcodesignasset/localcodesignasset.go, autocodesign/localcodesignasset/localcodesignasset_test.go, autocodesign/mock_LocalCodeSignAssetManager.go, autocodesign/profiles.go, autocodesign/utils.go, autocodesign/utils_test.go
Merging local and remote assets does not work properly when there are multiple export methods requested (such as development and ad-hoc), because the logic does not differentiate assets based on the export method.
- Ensure assets for each export method in a loop
- Thanks to this change, a lot of logic that worked on a `map[DistributionType]AppCodesignAssets` is simplified to a single `AppCodesignAssets` parameter
=> Handle local and remote codesign asssets for one distribution type

autocodesign/autocodesign.go, autocodesign/autocodesign_test.go, autocodesign/certificates.go, autocodesign/certificates_test.go, autocodesign/errors.go, autocodesign/localcodesignasset/localcodesignasset_test.go, autocodesign/projectmanager/projectmanager.go, codesign/codesign.go, xcarchive/ios.go, xcarchive/ios_test.go
Detecting team ID from the project settings takes considerable time, especially for large projects with many targets. The team ID is only used for:
- Apple ID based code signing and only if the authenticated account belongs to multiple teams
- Filtering local certificates found on the VM for the project's team ID. But even without this filtering, the next phase is to match local certs to ones downloaded from the Developer Portal, and those all belong to the correct team ID.
For the Apple ID based code path, users will be able to use the existing team ID step input if necessary.
- Remove team ID detection from `autocodesign/projectmanager`
- Remove `TeamID` field from `autocodesign.AppLayout`, the return type of `projectmanager`
- Remove team ID parameter from certificate processing …
=> Remove project team ID detection

autocodesign/devportalclient/appstoreconnect/time.go, autocodesign/devportalclient/appstoreconnect/time_test.go
We had an issue reported about failing to parse provisioning profiles: 
https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/issues/92
A quick fix was deployed to mitigate the error and this is a follow up improvement.
At first look the cause was that the returned time format has changed from 
```
2006-01-02T15:04:05.000-0700
```
to
```
2006-01-02T15:04:05.000-07:00
```
(there is an extra `:` delimiter).
The root cause is actually different. The returned dates are in the ISO 8601 format. In this standard some formats are interchangeable and equivalent to each other. The best example is this:
- 2006-01-02T15:04:05.000Z
- 2006-01-02T15:04:05.000+00:00
- 2006-01-02T15:04:05.000+0000
- 2006-01-02T15:04:05.000+00
represent the same date. The time parser needs to handle …
=> Better ISO 8601 time parsing

autocodesign/devices.go, autocodesign/devices_test.go, autocodesign/devportalclient/appstoreconnectclient/devices.go, autocodesign/devportalclient/appstoreconnectclient/devices_test.go, autocodesign/devportalclient/appstoreconnectclient/profiles.go, autocodesign/devportalclient/appstoreconnectclient/profiles_test.go, xcodecache/swiftpm_cache_test.go
Requires a *PATCH* [version update](https://semver.org/)
errors.As was incorrectly used:
```
rerr := appstoreconnect.ErrorResponse{} <-- & missing
if ok := errors.As(err, &rerr); ok {
```
Resolves: https://bitrise.atlassian.net/browse/STEP-1731
- Correctly detect  appstoreconnect.ErrorResponse.
- Fixed a bug when an incorrect device is encountered, other devices still sill be registered instead of returning early.
- Added retry for fetching a Bundle ID from a profile, if the profile has been removed.
=> Fix for device registration regression

exportoptionsgenerator/exportoptionsgenerator.go, exportoptionsgenerator/exportoptionsgenerator_test.go
Requires a *PATCH* [version update](https://semver.org/)
Include Xcode >12 specific export options even if an available profile/certificate is not found.
- distributionBundleIdentifier is requried for projects including App Clip
- manageAppVersionAndBuildNumber (Xcode>13) is also included for consistency
Due to the Automatic code signing feature it can happen that a given profile/certificate is not yet installed:
For example in xcode-archive Step:
- Archive is built (Xcode manages and downloads development provisioning profile)
- No custom exportOptions plist is provided, so the export options generator is called
- No Ad-hoc provisioning profile is found (as expected, is not yet downloaded)
- If the distributionBundleIdentifier is not included (a project with App Clip) it will lead to …
=> Include all export options even if profile is not found.

autocodesign/autocodesign.go, autocodesign/autocodesign_test.go
Requires a *PATCH* [version update](https://semver.org/)
Make sure the certificate is installed when a matching local profile is found.
Resolves: https://bitrise.atlassian.net/browse/STEP-1715
* Install certificate for locally found provisioning profiles. An alternative could have been to check weather certificate is already installed in the Keychain, always installing is the easier solution.
There was no check earlier that the selected certificate (or any certificate in the profile) was installed. This could have led to an error:
- A Step with automatic code signing installs **Profile1**, this induces **Cert1** and **Cert2**. **Cert1** is selected (to be set as signing certificate in the project). **Profile1** is added, **Cert1** is added to the Keychain. (**Cert2** is not added.)
- …
=> Intalling certificate for local codesign assets

xcarchive/ios.go
Requires a *PATCH* [version update](https://semver.org/)
Fixes an API incompatibility encountered in the export-xcarchive-step:
```
./main.go:204:32: cannot use a (type "github.com/bitrise-io/go-xcode/xcarchive".IosArchive) as type "github.com/bitrise-io/go-xcode/v2/xcarchive".IosArchive in argument to codesign.NewArchive
```
(needed for https://github.com/bitrise-steplib/steps-export-xcarchive/pull/38)
Resolves: https://bitrise.atlassian.net/browse/STEP-1788
=> Added NewIosArchive for API compatibility

autocodesign/keychain/keychain.go
Make sure keychain is unlocked before doing other keychain operations. Importing a certificate into a locked keychain could hang the command without any error.
Proof that it works: https://github.com/bitrise-steplib/steps-xcode-build-for-test/pull/29
=> Unlock keychain before other operations

autocodesign/devportalclient/spaceship/spaceship/devices.rb
We have received user complaint about the device registration failing the build. If you are using an Apple ID based connection and want to register a new device the autocodesign logic throws this error:
```
failed to manage code signing: failed to ensure test devices: failed to register Bitrise Test device on Apple Developer Portal: failed to unmarshal response: json: cannot unmarshal string into Go struct field .data.device of type spaceship.DeviceInfo
```
It is happening because 
```
{ device: device }
```
returns the following format
```
{
"device":"<Spaceship::Portal::Device id="ABCDEFG", name="Test name", udid="00000001-00000000000001", platform="ios", status="c", model="Test model", device_type="iphone">"
}
```
and the Go code expects a valid json and also different field names for …
=> Apply existing device processing logic for device registration response

profileutil/info_model_test.go, profileutil/util.go
There is a latent bug in parsing provisioning profiles that only affects macOS profiles. The profile type string value should have always been `osx` instead of `macos`, all the profiles I tested contain `osx` as the platform value.
This bug had been hidden by the parsing logic until we changed that: https://github.com/bitrise-io/go-xcode/pull/135/files#diff-bce396a3a6fcf20dea5ebb455b48500d48eb91b11baef46a7506c217d72b82b2
Note that the old code assigned macOS as the platform type by default and only changed it to iOS if it matched that platform. The new code does proper pattern matching for every possible platform, so it with `unknown platform type: macos` when parsing a macOS profile.
This is the root cause of https://github.com/bitrise-steplib/steps-export-xcarchive-mac/issues/13, …
=> Fix parsing of macOS profile types

xcodebuild/resolve_package_deps.go, xcodebuild/resolve_package_deps_test.go, xcodebuild/show_build_settings.go
Want to improve visibility of how much time resolving Swift packages takes; as part of the `-showBuildSettings` command especially.
* Added a `-resolvePackageDependencies` command builder
* Log elapsed time in the `-showBuildSettings` command
=> Adds resolvePackageDependencies command, logs elapsed time for showBuildSettings

codesign/inputparse.go, codesign/inputparse_test.go
Trying to clean up and unify the handling of certificates without a passphrase (which we allow uploading at the moment, so we should at least handle these certs consistently across all steps).
Related bug: https://github.com/bitrise-steplib/bitrise-step-manage-ios-code-signing/issues/8
First of all, there is no real bug fix in this PR. It turned out that this code in go-xcode already supports parsing of the list inputs with empty passphrase items. The problem is on the step side where we marked the passphrase list input as required, so a single item of empty passphrase is an invalid step input.
This PR improves the following:
- Add tests for input parsing to make it explicit that we support empty passphrases
- Improve log messages here and there
=> Improve empty passphrase handling

autocodesign/autocodesign_test.go, autocodesign/devportalclient/appstoreconnect/profiles.go, autocodesign/devportalclient/appstoreconnect/time.go, autocodesign/devportalclient/spaceship/profiles.go, autocodesign/devportalclient/time/time.go, autocodesign/devportalclient/time/time_test.go, autocodesign/localcodesignasset/localcodesignasset_test.go, autocodesign/localcodesignasset/profileconverter.go, autocodesign/profiles_test.go, autocodesign/utils_test.go
There is a few cases when Apple ID login does not work (`Please update to Xcode 7.3` https://github.com/bitrise-steplib/steps-xcode-archive/issues/287). Setting `SPACESHIP_AVOID_XCODE_API=true` can be used as a workaround, but that can only succeed with recognizing a different timestamp format in the listed profiles.
https://github.com/bitrise-steplib/steps-xcode-archive/issues/288
=> [NOJIRA] Add support for time format returned by Spaceship with SPACESHIP_AVOID_XCODE_API=true

xcodecache/swiftpm_cache.go
To be reviewed together with https://github.com/bitrise-steplib/steps-xcode-test/pull/204
This is just a small change to make sure current cache handling works with Swift package projects, not just with Xcode workspaces/projects.
=> Add support for Swift Package projects in cache handling

destination/destination.go, destination/simulator.go, destination/simulator_test.go
Requires a *MINOR* [version update](https://semver.org/)
`xcodebuild build-for-testing` places the built targets and tests into the built test dir. The name of this dir depends on the build destination:
- For iOS Device (and Debug configuration) it looks like: `Debug-iphoneos`
- For iOS Simulator (and Debug configuration) it looks like: `Debug-iphonesimulator`
This PR introduces `destination.Specifier` struct to support the [improvement of how xcode-build-for-test step determines the built test dir name](https://github.com/bitrise-steplib/steps-xcode-build-for-test/pull/39#discussion_r896922993).
- introduce `destination.Specifier`
The available platforms (Xcode 14) are listed in the destination package, but not used by this package directly. 
The purpose is to support the consumer side …
=> Destination specifier

codesign/codesign.go, codesign/codesign_test.go, codesign/inputparse.go, codesign/inputparse_test.go, go.mod, go.sum
Code signing steps should be able to override the App Store Connect connection details by step inputs.
This PR adds common code to all steps that will handle connection override inputs.
- Add a method that validates and parses connection parameters
- Path to private key can be either a local file path or a remote URL, the code handles both and returns with the raw contents
=> Add API connection override input parsing

codesign/codesign.go, codesign/inputparse.go, codesign/inputparse_test.go
Requires a *MINOR* [version update](https://semver.org/)
Update `codesign.ParseConfig` and `codesign.SelectConnectionCredentials` error messages.
- Wrap errors with `%w`
- Improve function names called by `codesign.ParseConfig`
- Improve error messages
`codesign.ParseConfig` new errors:
```
code signing certificate URL is not specified
code signing certificate count (%d) and passphrase count (%d) should match
keychain path is not specified
keychain password is not specified
failed to open keychain: %w
invalid provisioning profile URL specified (%s): %w
failed to check if provisioning profile path exists (%s): %w
directory of provisioning profiles does not exist (%s)
failed to list entries of the provisioning profiles directory (%s): %w
```
`codesign.SelectConnectionCredentials` new …
=> Plang 2392 error messages

.golangci.yml, autocodesign/autocodesign_test.go, autocodesign/certdownloader/certdownloader.go, autocodesign/devportalclient/appstoreconnectclient/devices_test.go, autocodesign/errors.go, autocodesign/profiledownloader/profiledownloader.go, autocodesign/projectmanager/projecthelper_test.go, bitrise.yml, destination/device_finder.go, xcarchive/ios_test.go, xcpretty/xcpretty.go
Use the standard linters and config we use in other step repos.
This PR drops errcheck and golint in favor of golangci-lint through the check internal step.
There were a few lint violations with the new rules, this PR fixes those.
```
xcarchive/ios_test.go:68:9: composites: github.com/bitrise-io/go-xcode/xcarchive.IosExtension struct literal uses unkeyed fields (govet)
{
^
xcarchive/ios_test.go:93:8: composites: github.com/bitrise-io/go-xcode/xcarchive.IosExtension struct literal uses unkeyed fields (govet)
{
^
xcarchive/ios_test.go:104:8: composites: github.com/bitrise-io/go-xcode/xcarchive.IosExtension struct literal uses unkeyed fields (govet)
{
^
autocodesign/devportalclient/appstoreconnectclient/devices_test.go:18:9: copylocks: Do passes lock by value: …
```
=> Use standard linters

errorfinder/errorfinder.go, errorfinder/errorfinder_test.go, errorfinder/nserror.go
It seems like the xcodebuild error formats are generic and shared between all of the xcodebuild subcommands. The xcode-test step was producing similar errors as the xcode-archive one. 
This PR extracts and adds test to the already existing custom xcodebuild error finder logic which at the moment only lives in the xcode-archive step: https://github.com/bitrise-steplib/steps-xcode-archive/blob/9f4ef188d017b110374ea71ba9445bae1acfa6ef/step/errors.go
=> [CI-267] Add generic xcodebuild error finder

devportalservice/devportalservice.go, devportalservice/testdevice.go, devportalservice/testdevice_test.go
Bitrise does not provide a proper device management for the users. This PR does not aim to solve that but rather adding an extra easy way managing the test devices. 
The users will be able to provide a path to a file which contains a comma separated list of device identifiers. If this input is set then it will have priority over the Bitrise service connection. 
This parsing logic will be used by three steps:
- steps-xcode-archive
- steps-export-xcarchive
- steps-xcode-build-for-test
And here are some links to see how these changes would look in the steps:
- https://github.com/bitrise-steplib/steps-xcode-archive/compare/CI-615-file-based-device-list?expand=1
- https://github.com/bitrise-steplib/steps-export-xcarchive/compare/CI-615-file-based-device-list?expand=1
- …
=> [CI-615] File based device parsing

destination/device_finder.go, destination/device_finder_test.go, destination/parse.go, destination/testdata/testout.go
We want to remove hardcoded device names (`iPhone 8 Plus`) from Step inputs.
On most Stacks there is a default device created, the Steps will use that by default. If the default device is not available, will use the first available device.
=> Adding support for default Bitrise device.

pathfilters/pathfilters.go, pathfilters/pathfilters_test.go, pathfilters/pathfilters_testdata.go
In the recent Xcode version when creating a new project a Multiplatform App is the default initial configuration. Such a project can be built for iOS and macOS platforms too.
These projects' `SDKROOT` target build setting is set to `auto` and has a `SUPPORTED_PLATFORMS` target build setting with `"iphoneos iphonesimulator macosx"` value. 
This setup is not considered an iOS project by the project scanner, because the `pathfilters.SDKFilter` expects `SDKROOT=iphoneos`.
This PR updates `pathfilters.SDKFilter` to use the `SUPPORTED_PLATFORMS` target build settings when deciding if the given project can be built with the given SDK or not.
JIRA ticket: https://bitrise.atlassian.net/browse/BIVS-1998
- Update `pathfilters.SDKFilter` to utilize `SUPPORTED_PLATFORMS` target build settings
- Test …
=> Supported platforms

destination/device_finder.go, destination/device_finder_test.go, destination/parse.go, destination/xcode_runtime_support.go, destination/xcode_runtime_support_test.go
When Xcode 14.3 and Xcode 15 (beta)  is present on the same machine, requiring the `latest` (this is the default) version of the Simulator runtime, will find iOS 17 (beta). This is undesirable as the beta Simulator can be unstable or at least not officially supported by earlier Xcodes.
In practice Xcode still works with newer runtimes, at least across the same major version (despite this table: https://developer.apple.com/support/xcode/). When there are different major versions, there is some risk of not working right.
```
Input:
- xctestrun: /var/folders/69/qgnyrbkx23dbp0p6p_b6bc9m0000gn/T/test_bundle928674358/BullsEye_FullTests_iphonesimulator16.4-arm64-x86_64.xctestrun
- destination: platform=iOS Simulator,name=iPhone 12 Pro Max
- xcodebuild_options: -parallel-testing-enabled YES
- …
```
=> [BE-1124] Limit iOS simulator runtime to runtimes released for a given Xcode

simulator/simulator.go, simulator/simulator_test.go
Add arch flag to Simulator when booting, this allows booting Simulator in Rosetta mode.
=> Add support for simulator arch flag

xcodeproject/xcodeproj/schemes.go, xcodeproject/xcodeproj/schemes_test.go, xcodeproject/xcworkspace/schemes.go, xcodeproject/xcworkspace/schemes_test.go
This PR fixes an issue with the new Xcode scheme listing.
When the logic founds a workspace setting file, but the `IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded` key doesn't present in it, the function failed with:
```
listing schemes in Xcode workspace at <workspace_path>.xcworkspace failed: key: string("IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded") not found in: serialized.Object(serialized.Object{"BuildSystemType":"Original"})
```
This shouldn't happen, since the Autocreate schemes option is enabled by default.
=> Fix workspace settings key not found handling

go.mod, go.sum
This PR updates the go-xcode v1 dependency on go-xcode v2, to pull the latest scheme listing fix: https://github.com/bitrise-io/go-xcode/pull/211
=> Update go-xcode v1 dep

destination/device_finder.go, destination/errors.go, destination/parse.go
When the destination specifier of the xcode-test step contains an invalid destination, the error messages are cryptic and not very helpful. This PR improves all the related error messages, including suggestions wherever possible.
- Improve returned errors
- Rename a few vars and fields to make the clone easier to understand
- Tests: it's not visible in the diff, but `device_finder_test.go` tests this logic extensively
=> Improve simulator-related error messages

autocodesign/projectmanager/projecthelper.go, go.mod, go.sum
This change will propagate the errors occurring during the scheme listing phase. 
It will also update the v1 version to the latest one which adds extra context to errors:
https://github.com/bitrise-io/go-xcode/pull/216
=> Propagate scheme error

destination/destination.go, destination/parse.go, simulator/simulator.go
Add support for handling `visionOS` destinations, devices, platform lookups, etc.
Tested in https://github.com/bitrise-steplib/bitrise-step-xcode-start-simulator/pull/10
=> Add visionOS Simulator as platform

autocodesign/devportalclient/spaceship/spaceship.go
We logged potential secrets due to using the v2/command package: https://github.com/bitrise-io/go-utils/blob/921272de13f5811b3a22dcd883459ea472c7f461/command/command.go#L172.
```Apple ID authentication failed: The input stream is exhausted., error: command failed with exit status 1 (bundle "exec" "ruby" "main.rb" "--subcommand" "list_dev_certs" "--username" "myemail@gmail.com" "--password" "my-readable-password" "--session" ```
Fixed this by omitting the error returned by v2/command.
=> Do not log sensitive command params

autocodesign/devportalclient/spaceship/spaceship.go, autocodesign/devportalclient/spaceship/spaceship/main.rb, autocodesign/devportalclient/spaceship/spaceship/portal/auth_client.rb
This PR fixes a regression introduced in this recent PR: https://github.com/bitrise-io/go-xcode/pull/226.
Spaceship login automatically sets the Apple developer team on the spaceship client when it is not specified explicitly. The logic selects the single Apple developer team to which the given Apple developer account belongs, or to the first team when it belongs to multiple teams.
After the first spaceship login, we don't do further logins, just restore a client. On this restored client the automatic team selection is not happening, so we need to do it manually, to avoid this issue:
```
Apple provided the following error info: Please select a team.
```
=> Set current team id after spaceship login on the spaceship client

exportoptionsgenerator/certificates.go, exportoptionsgenerator/exportoptionsgenerator.go, exportoptionsgenerator/exportoptionsgenerator_test.go, exportoptionsgenerator/profiles.go, exportoptionsgenerator/targets.go, go.mod, go.sum
This PR reorganizes the files in the `exportoptionsgenerator` package and adds support for the automatic signing style.
The `exportoptionsgenerator` package new organisation:
- `ExportOptionsGenerator` dependencies are moved to their own files, to shorten the code in `exportoptionsgenerator.go`
- Const, Types, and exported funcs are at the top of the files
Automatic signing style support:
- the `provisioningProfiles` entry shouldn't be in the exportOptions.plist when the IPA export is Xcode managed
=> Add support for automatic signing style

bitrise.yml, exportoptions/appstore_options.go, exportoptions/exportoptions_test.go, exportoptions/properties.go
Export Options now supports a `testFlightInternalTestingOnly` boolean option for app-store distribution method. 
This pull request adds that option to v1
=> added testFlightInternalTestingOnly appStore option

xcodecommand/xcbeautify.go, xcodecommand/xcodebuild_only.go, xcodecommand/xcpretty.go
The xcodebuild command had this env set, but not xcbeautify; as we use go pipes not the bash command ` NSUnbufferedIO=YES xcodebuild [args] 2>&1 | xcbeautify` (reccomended by xcbeatify).
This may affect xcbeautify behaviour, and may solve some "hangs".
See: https://developer.apple.com/library/archive/technotes/tn2124/_index.html
```
NSUnbufferedIO
If set to YES, Foundation will use unbuffered I/O for stdout (stderr is unbuffered by default) 
```
=> Add NSunbufferedIO env to xcbeautify too

autocodesign/autocodesign.go, autocodesign/autocodesign_test.go, autocodesign/devportalclient/appstoreconnect/bundleids.go, autocodesign/devportalclient/appstoreconnect/certificates.go, autocodesign/devportalclient/appstoreconnect/devices.go, autocodesign/devportalclient/appstoreconnect/error.go, autocodesign/devportalclient/appstoreconnect/profiles.go, autocodesign/devportalclient/appstoreconnectclient/certificates.go, autocodesign/devportalclient/appstoreconnectclient/devices.go, autocodesign/devportalclient/appstoreconnectclient/profiles.go, autocodesign/devportalclient/spaceship/profiles.go, autocodesign/localcodesignasset/localcodesignasset_test.go, autocodesign/localcodesignasset/profile.go, autocodesign/localcodesignasset/profilelookup.go, autocodesign/mock_Profile.go, autocodesign/profiles.go, autocodesign/profiles_test.go
- Added fallbacks for paging API error (invalid cursor). In case the existing paging logic fails, we use workarounds such as fetch400Profiles.
- Removed API calls for devices included in profiles, this should help with rate limits in the long term. To do this we use the UDIDs to check for profile validity, instead of the opaque ID from the API.
=> [SSW-2210] Paging workarounds and improvements

xcodebuild/build.go, xcodebuild/build_test.go, xcodebuild/export.go, xcodebuild/export_test.go
Added CommandArgs function for the xcodebuild CommandBuilder, this removes the dependency on the v1 command package and helps with xcbeautify support integration.
The existing xcodecommand package only requires xcodebuild arguments, with this change we do no need:
```go
xcodebuildCmdWithArgs := archiveCmd.ExecCommand().Args
if len(xcodebuildCmdWithArgs) == 0 {
panic("")
}
onlyArgs = xcodebuildCmdWithArgs[1:]
```
only:
```go
onlyArgs := archiveCmd.CommandArgs()
```
=> Getter for xcodebuild command arguments

autocodesign/devportalclient/appstoreconnect/appstoreconnect.go, autocodesign/devportalclient/appstoreconnect/error.go
Apple API (especially enterprise) can return intermittent agreement missing errors, even when not the case.
=> Adding retry when agreements missing

codesign/codesign.go
This PR fixes the fallback profile mechanism for UITest targets and updates `codesign.Manager.PrepareCodesigning` to retrun info of the managed signing assets.
=> Fallback profiles fix: add support for UITest targets
